name: Django Tests

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: filesdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root123
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt

    - name: Copy local.env
      run: |
        cp local.env .env
      working-directory: ${{ github.workspace }}

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 app
      working-directory: ${{ github.workspace }}/app

    - name: Coverage Report
      run: |
        pip install coverage
        coverage run --source=app manage.py test
        coverage report --omit="*/migrations/*"
      working-directory: ${{ github.workspace }}/app

    - name: Django Testing
      run: |
        python manage.py test
      working-directory: ${{ github.workspace }}/app
