name: Django Tests

on:
  push:
    branches:
      -master
  
  pull_request:
    branches:
      -master

jobs:
  build:
    
    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@v2
    - name: Set Up Python 3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r app/requirements/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
      working-directory: ./app 
    - name: Coverage Report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
      working-directory: ./app 
    - name: Django Testing
      run: |
        python3 manage.py test
      working-directory: ./app 

